language: ruby
rvm:
 - 2.2
# uncomment this line if your project needs to run something other than `rake`:
script: bundle _1.11.2_  install

branches:
  only:
    - master
    
notifications:
  email:
    - dcaro@microsoft.com 
