language: ruby
rvm:
 - 2.2.4
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec

branches:
  only:
    - master
    
notifications:
  email:
    - dcaro@microsoft.com 