# Site settings
title: DevOps team Case Studies
email: dcaro@microsoft.com
# description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://microsoftdevops.github.io" # the base hostname & protocol for your site
twitter_username: dcaro
github_username:  microsoftdevops
encoding: utf-8

# Build settings
# markdown: redcarpet
# highlighter: pygments
# extensions: [tables fenced_code_blocks]

exclude: [vendor]
kramdown:
   input: GFM
gems:
  - jekyll-sitemap